// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_mhKSmuvv_Qc-GzylMCKwzY54SMCg7Hc',
    appId: '1:874979013240:web:59106b33dff38e6424f38d',
    messagingSenderId: '874979013240',
    projectId: 'jaramarket-vendor',
    authDomain: 'jaramarket-vendor.firebaseapp.com',
    storageBucket: 'jaramarket-vendor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm-tpACJHsdDULUCC7DoeJRyOIfbH-HAg',
    appId: '1:874979013240:android:7206e6258eaa913224f38d',
    messagingSenderId: '874979013240',
    projectId: 'jaramarket-vendor',
    storageBucket: 'jaramarket-vendor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL4UK7C4UZtVqoR19xLWudXnL3oiXcOk8',
    appId: '1:874979013240:ios:3888665dac4ff68a24f38d',
    messagingSenderId: '874979013240',
    projectId: 'jaramarket-vendor',
    storageBucket: 'jaramarket-vendor.firebasestorage.app',
    iosBundleId: 'com.jaramarket.vendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL4UK7C4UZtVqoR19xLWudXnL3oiXcOk8',
    appId: '1:874979013240:ios:f6ba139aade65a7524f38d',
    messagingSenderId: '874979013240',
    projectId: 'jaramarket-vendor',
    storageBucket: 'jaramarket-vendor.firebasestorage.app',
    iosBundleId: 'com.jara.vendor.jaraVendor',
  );
}
